import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navBar"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pets Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head>
        <link rel="preconnect" href="<https://app.snipcart.com>" />
        <link rel="preconnect" href="<https://cdn.snipcart.com>" />
        <link
          rel="stylesheet"
          href="https://cdn.snipcart.com/themes/v3.2.0/default/snipcart.css"
        />
      </head> */}
      <body className={inter.className}>
        <NavBar />
        {children}
      {/* <script async src="https://cdn.snipcart.com/themes/v3.2.0/default/snipcart.js"></script>
      <div hidden id="snipcart" data-api-key="MzEwZDg0MDctYjY4YS00YzcyLTlmMzAtZDVlNGI2YjAzNGI2NjM4NDY5NjM5MTM2NzYzNjc1"></div> */}
      </body>
      
    </html>
  );
}
